# Generated by Django 2.0.2 on 2018-03-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_wallet_address', models.TextField()),
                ('master_wallet_password', models.CharField(max_length=100)),
                ('node_url', models.URLField()),
            ],
        ),
    ]
