# Generated by Django 2.0.2 on 2018-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
