# Generated by Django 2.0.2 on 2018-04-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_userwallet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='tx_hash',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
